### ISSUE TITLE
Use pow() when available

### ISSUE THREAD

**Issue by KittyGiraudel** [hiulit/Sassy-Gridlover#4]
You could make your [exponent()](https://github.com/hiulit/Sassy-Gridlover/blob/master/sassy-gridlover/_sassy-gridlover.scss#L4) function use `pow` for Compass, Sassy-Math or whatever when available.

``` scss
@function exponent($base, $exponent) {
    @if pow(2, 2) == 4 {
        @return pow($base, $exponent);
    }

    // Resets value.
    $value: $base;
    // Positive intergers get multiplied.
    @if $exponent > 1 {
        @for $i from 2 through $exponent {
            $value: $value * $base; } }
    // Negatives intergers get divided. A number divided by itself is 1.
    @if $exponent < 1 {
        @for $i from 0 through -$exponent {
            $value: $value / $base; } }
    // Return the last value written.
    @return $value;
}
```
